### ISSUE TITLE
Review doesn't appear

### ISSUE THREAD

**Issue by tbtommyb** [NodeGroup2/OCD-B#67]
I logged in and did a review of CS50 but it hasn't appeared in recent reviews or my reviews?

**Comment by tbtommyb** [comment]
But then I refreshed and it was under 'my reviews' (but not 'recent'). But it seems the redirect happens before the review is in the DB (I will check the code)?

**Comment by msachi** [comment]
Yup, we're aware of this, it's because of how (incorrectly) handle callbacks. Thanks!
