### ISSUE TITLE
Requiring routes

### ISSUE THREAD

**Issue by otajor** [NodeGroup2/OCD-B#70]
https://github.com/NodeGroup2/OCD-B/blob/master/src/routes.js#L1-L5
The way you've done it is fine - an alternative (maybe DRYer) pattern we like for requiring routes is: 
```javascript
const routes = [
  './routes/login.js',
  './routes/register.js',
  './routes/dynamic.js'
].map(require)
```

**Comment by otajor** [comment]
Hmm actually now I see you have multiple routes in some of your route files - this wouldn't work as I've written it, you would have to concat them or something.

**Comment by sohilpandya** [comment]
yeah, I was going to say something along the lines, but I would really recommend that you guys have each route in its own file rather than having 2/3 in one file. https://github.com/NodeGroup2/OCD-B/blob/master/src/routes/dynamic.js
